---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: tf-aws
  namespace: flux-system
spec:
  interval: 1m
  #approvePlan: auto
  path: ./
  sourceRef:
    kind: GitRepository
    name: tf-aws
    namespace: flux-system
  tfstate:
    forceUnlock: "yes"
    lockIdentifier: a5124beb-3cfc-cbab-3c10-de7e14f14ea4
  storeReadablePlan: human
  varsFrom:
  - kind: Secret
    name: aws-credentials
    varsKeys:
    - access
    - secret
