---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tf-controller-crs
  namespace: flux-system
spec:
  dependsOn:
    - name: apps
      namespace: flux-system
  interval: 1m
  path: ./apps/tf-controller/crs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
