---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: tf-aws
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/al-lac/tf-aws
  ref:
    branch: main
  ignore: |
    # include all
    !/**
